apiVersion: authenticated.cloudflare.crossplane.io/v1alpha1
kind: OriginPullsSettings
metadata:
  annotations:
    meta.upbound.io/example-id: authenticated/v1alpha1/originpullssettings
  labels:
    testing.upbound.io/example-name: example_authenticated_origin_pulls_settings
  name: example-authenticated-origin-pulls-settings
spec:
  forProvider:
    enabled: true
    zoneId: 023e105f4ecef8ad9ca31a8372d0c353
